import { FeedPostType } from '../types';

export const getBlogFeed = async (): Promise<FeedPostType[]> => {
  return [
    {
      id: '1',
      authorId: 'user123',
      title: "Exploring Markdown in Blog Posts!",
      content: 'Item 1\n- Item 2\n\n**Bold** text!',
      imageUrl: 'http://tripjogja.co.id/wp-content/uploads/2017/04/Malioboro-01-1024x576.jpg',
      tags: ['markdown', 'blog', 'nextjs'],
      loveCount: 20,
      commentCount: 5,
      shareCount: 2,
      createdAt: '2025-08-06T10:00:00Z',
    },
    {
      id: '2',
      authorId: 'user456',
      title: "Short blog with just text.",
      content: 'content',
      tags: ['text-only'],
      loveCount: 5,
      commentCount: 0,
      shareCount: 0,
      createdAt: '2025-08-05T08:30:00Z',
    },
    {
        id: '1',
        authorId: 'user123',
        title: "Exploring Markdown in Blog Posts!",
        content: 'Item 1\n- Item 2\n\n**Bold** text!',
        imageUrl: 'http://tripjogja.co.id/wp-content/uploads/2017/04/Malioboro-01-1024x576.jpg',
        tags: ['markdown', 'blog', 'nextjs'],
        loveCount: 20,
        commentCount: 5,
        shareCount: 2,
        createdAt: '2025-08-06T10:00:00Z',
      },
      {
        id: '1',
        authorId: 'user123',
        title: "Exploring Markdown in Blog Posts!",
        content: 'Item 1\n- Item 2\n\n**Bold** text!',
        imageUrl: 'http://tripjogja.co.id/wp-content/uploads/2017/04/Malioboro-01-1024x576.jpg',
        tags: ['markdown', 'blog', 'nextjs'],
        loveCount: 20,
        commentCount: 5,
        shareCount: 2,
        createdAt: '2025-08-06T10:00:00Z',
      },
      {
      id: '1',
      authorId: 'user123',
      title: "Exploring Markdown in Blog Posts!",
      content: 'Item 1\n- Item 2\n\n**Bold** text!',
      imageUrl: 'http://tripjogja.co.id/wp-content/uploads/2017/04/Malioboro-01-1024x576.jpg',
      tags: ['markdown', 'blog', 'nextjs'],
      loveCount: 20,
      commentCount: 5,
      shareCount: 2,
      createdAt: '2025-08-06T10:00:00Z',
    },
  ];
};