import { UserType } from '../_types';

export const getMockUser = (): UserType => ({
  id: '1',
  name: 'Angga Wika Nugraha',
  username: 'anggawika',
  bio: 'Frontend Engineer passionate about building web and mobile with React & next.js.',
  email: 'anggawika18@gmail.com',
  phone: '088228925868',
  location: 'Jakarta, Indonesia',
  avatarUrl: 'https://media.licdn.com/dms/image/v2/D5603AQFx0LkAHjx-3w/profile-displayphoto-shrink_400_400/profile-displayphoto-shrink_400_400/0/1716261567983?e=1757548800&v=beta&t=QZrY-jy7s3pRI2hAu9ZD9Ja3g-GOy6KdOF0E0SJYEjE',
  jobTitle: 'Frontend Engineer',
  company: 'Qlola by BRI',
  website: 'https://anggawika.dev',
  social: {
    github: 'https://github.com/AnggaWikaNugraha',
    linkedin: 'https://www.linkedin.com/in/angga-w-a45b0111a/',
  },
  skills: [
    'React', 'React native', 'Next.js',
    'TypeScript',
    'redux', 'redux-toolkit', 'Redux Thunk', 'React Context APi',
    'React Hook Form', 'formik', 'yup validator',
    '⁠⁠swr', 'axios',
    'React Testig Library', 'jest',
    'Tailwind CSS', 'bootstrap', 'material ui', 'ant desain',
    'Agora WebRTC',
    'Mock Service Worker',
    'Git',
    'scrum',
  ],
  interests: ['Open Source', 'MFE', 'CSR/SSR'],
  experience: [
    {
      id: 'exp1',
      company: 'PT. Bank Rakyat Indonesia (Persero) Tbk',
      companyLogoUrl: 'https://media.licdn.com/dms/image/v2/C560BAQESeeSifohmkw/company-logo_100_100/company-logo_100_100/0/1630662965246/pt_bank_rakyat_indonesia_persero_tbk_logo?e=1757548800&v=beta&t=wkyu8C0B7S7p27wf00KixwwwDCYCxxG6GRBxif4fRno',
      location: 'Jakarta',
      roles: [
        {
          id: 'role1',
          title: 'Frontend Engineer',
          employmentType: 'Fulltime',
          startDate: '2025-01-01',
          endDate: undefined,
          duration: '7 bulan',
          description: 'Developing web applications using Next.js MFE',
          skills: ['React', 'Next.js'],
        },
      ],
    },
    {
      id: 'exp2',
      company: 'Telkom',
      companyLogoUrl: 'https://media.licdn.com/dms/image/v2/C4D0BAQGVLh28SyAv-g/company-logo_100_100/company-logo_100_100/0/1631315215307?e=1758153600&v=beta&t=C8H9ADO4Q5TzBSj8Ly8a4bCq5WMfvP5p8TsnGwh40x0',
      location: 'Jakarta',
      roles: [
        {
          id: 'role1',
          title: 'Frontend Engineer At Talent Engine',
          employmentType: 'Freelance',
          startDate: '2024-04-01',
          endDate: undefined,
          duration: '1 tahun 5 bulan',
          description: 'Developing web applications using React',
          skills: ['React', 'Next.js'],
        },
        {
          id: 'role2',
          title: 'Frontend Engineer At Metranet',
          employmentType: 'Fulltime',
          startDate: '2022-01-01',
          endDate: '2022-05-01',
          duration: '2 tahun 5 bulan',
          description: 'Developing web applications using React',
          skills: ['React', 'Next.js'],
        },
      ],
    },
  ],
  education: [
    {
      id: 'edu1',
      school: 'Universitas Muhammadiyah Yogyakarta',
      degree: 'S1',
      fieldOfStudy: 'Teknologi Informasi',
      startYear: 2017,
      endYear: 2021,
      description: 'Belajar dasar pemrograman dan pengembangan perangkat lunak.',
    },
  ],
  certificates: [
    // {
    //   id: 'cert1',
    //   title: 'React Developer Certification',
    //   issuer: 'Udemy',
    //   issueDate: '2023-06-10',
    //   credentialUrl: 'https://cert.udemy.com/react-cert',
    // },
  ],
  createdAt: '2022-01-01T00:00:00Z',
});